import express from 'express';
import { authUser, deleteUsers, getAllUsers, getUserProfile, logoutUser, registerUser, updateUserProfile } from '../controllers/userController.js';
import { userControlAuth } from '../middleware/authMiddleWare.js';
const router = express.Router();
router.post('/register', registerUser);
router.post('/auth', authUser);
router.post('/logout', logoutUser);
router.route('/profile').get(userControlAuth, getUserProfile).put(userControlAuth, updateUserProfile);
router.get('/all', userControlAuth, getAllUsers);
router.delete('/all/:id', userControlAuth, deleteUsers);
export default router;